extends:
  - airbnb-base
  - plugin:jest/recommended
  - plugin:jest/style
  - plugin:prettier/recommended

env:
  es2021: true
  jest: true

plugins:
  - simple-import-sort

parserOptions:
  ecmaVersion: 2021
  sourceType: module

rules:
  class-methods-use-this: off
  import/order: off
  import/extensions: [error, always]
  no-console: off
  no-underscore-dangle: off
  simple-import-sort/exports: error
  simple-import-sort/imports: error
  sort-imports: off

overrides:
  - files: ['*.ts', '*.tsx']
    extends:
      - airbnb-typescript/base
      - plugin:@typescript-eslint/recommended
    parser: '@typescript-eslint/parser'
    parserOptions:
      project: tsconfig.json
    rules:
      '@typescript-eslint/indent': off
