name: CI

on:
  push:
    branches: [main]
    paths-ignore: ['*.md', LICENSE, .gitignore, .husky/**]
  pull_request:
    branches: [main]
    paths-ignore: ['*.md', LICENSE, .gitignore, .husky/**]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  HUSKY: 0
  NODE_VERSION: 16

jobs:
  lint:
    name: Lint & format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install
        id: install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Format
        if: always() && steps.install.outcome == 'success'
        run: npm run format

  typecheck:
    name: Check types
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Test
        run: npm run test:cov

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
